### ISSUE TITLE
I have encountered some problems when using hixo+github to build a personal blog, I hope to get your help.

### ISSUE THREAD

**Issue by fenqingyang-sys** [jondot/hygen#143]
After setting up the local hexo, when I configured the _config file in the hexo directory, after the configuration is completed, using cmd to input the hexo d -g command in windows, the following error occurs: 

D:\hexo>hexo d -g
FATAL can not read a block mapping entry; a multiline key may not be an implicit key at line 94, column 1:

    ^
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 94, column 1:

    ^
    at generateError (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at readBlockMapping (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1073:9)
    at composeNode (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
    at readDocument (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1519:3)
    at loadDocuments (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
    at Object.load (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
    at Hexo.yamlHelper (D:\hexo\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.then.text (D:\hexo\node_modules\hexo\lib\hexo\render.js:60:20)
    at tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\hexo\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\hexo\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\hexo\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\hexo\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\hexo\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)

I haven't found the cause of the problem for a day. I hope I can get your help. Thank you very much.

**Comment by anithri** [comment]
I'm afraid you have the wrong repo.
