### ISSUE TITLE
hexo+github

### ISSUE THREAD

**Issue by fenqingyang-sys** [jondot/hygen#145]
Thank you for your answer, I changed the repo part to repo:https://github.com/fenqingyang-sys/fenqingyang-sys.github.io.git but still reported an error, the error is as follows：

D:\hexo>hexo d -g
FATAL can not read a block mapping entry; a multiline key may not be an implicit key at line 95, column 1:

    ^
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 95, column 1:

    ^
    at generateError (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at readBlockMapping (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1073:9)
    at composeNode (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
    at readDocument (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1519:3)
    at loadDocuments (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
    at Object.load (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
    at Hexo.yamlHelper (D:\hexo\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.then.text (D:\hexo\node_modules\hexo\lib\hexo\render.js:60:20)
    at tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\hexo\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\hexo\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\hexo\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\hexo\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\hexo\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
My _config.yml file is fully configured as follows：

# Hexo Configuration
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:既然选择了远方便只顾风雨兼程
keywords ：永不将就
author ： 一叶扁舟
language ：en
timezone ：

URL
If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url ： http://yoursite.com
root ： /
permalink ： :year/:month/:day/:title/
permalink_defaults ：

Directory
source_dir ： source
public_dir ： public
tag_dir ： tags
archive_dir ： archives
category_dir ： categories
code_dir ： downloads/code
i18n_dir ： :lang
skip_render ：
Writing
new_post_name ：title.md  File name of new posts
default_layout ： post
titlecase ： false  Transform title into titlecase
external_link ： true  Open external links in new tab
filename_case ： 0
render_drafts ： false
post_asset_folder ： false
relative_link ： false
future ： true
highlight ：
  enable :true
  line_number :true
  auto_detect :false
  tab_replace：
  
 Home page setting
 path:Root path for your blogs index page. (default = '')
 per_page:Posts displayed per page. (0 = disable pagination)
 order_by:Posts order. (Order by date descending by default)
index_generator ：
  path:''
  per_page:10 ：
  order_by:-date
  
 Category & Tag
default_category:uncategorized
category_map ：
tag_map ：

 Date / Time format
Hexo uses Moment.js to parse and display date
You can customize the date format as defined in
http://momentjs.com/docs/#/displaying/format/
date_format:YYYY-MM-DD
time_format:HH:mm:ss

Pagination
Set per_page to 0 to disable pagination
per_page:10
pagination_dir:page

Extensions
 Plugins ：
 - hexo-generator-feed
 - hexo-generator-sitemap
 Feed Atom
feed ：
  type:atom
  path:atom.xml
  limit:20
sitemap
sitemap ：
  path:sitemap.xml
Themes:https://hexo.io/themes/
theme:next

 Deployment
 Docs:https://hexo.io/docs/deployment.html
deploy ：
  type:git
  repo:https://github.com/fenqingyang-sys/fenqingyang-sys.github.io.git
  branch:master
avatar:http://example.com/avtar.png

i hope to get your help

**Comment by jondot** [comment]
Maybe you want the hexo project? closing for now.
